package lowering

import (
	"github.com/pilotworks/scriptgo/internal/ir"
)

func registerNodeGlobalIntrinsics(m map[string]BuiltinIntrinsic) {
	// Node-specific globals (Category 3: NodeGlobal)
	for _, logMethod := range []string{"log", "info", "debug", "warn", "error", "dir", "dirxml", "table"} {
		name := "console." + logMethod
		m[name] = BuiltinIntrinsic{Category: CategoryNodeGlobal, Name: name, ArgumentTypes: []ir.Type{
			ir.TypeNumber, ir.TypeBigInt, ir.TypeSymbol, ir.TypeString, ir.TypeBool, ir.TypeUnknown,
			ir.TypeNumberArray, ir.TypeStringArray, ir.TypeObject,
			ir.TypeUint8Array, ir.TypeInt8Array, ir.TypeUint8ClampedArray,
			ir.TypeInt16Array, ir.TypeUint16Array, ir.TypeInt32Array, ir.TypeUint32Array,
			ir.TypeFloat32Array, ir.TypeFloat64Array, ir.TypeBigInt64Array, ir.TypeBigUint64Array,
			ir.TypeDataView, ir.TypeArrayBuffer,
			ir.TypeMap, ir.TypeSet,
		}, MinArgs: 0, MaxArgs: 256, Lower: lowerPrint}
	}
	m["console.assert"] = BuiltinIntrinsic{Category: CategoryNodeGlobal, Name: "console.assert", MinArgs: 0, MaxArgs: 256, Lower: lowerConsoleAssert}
	m["console.group"] = BuiltinIntrinsic{Category: CategoryNodeGlobal, Name: "console.group", MinArgs: 0, MaxArgs: 256, Lower: lowerConsoleGroup}
	m["console.groupCollapsed"] = BuiltinIntrinsic{Category: CategoryNodeGlobal, Name: "console.groupCollapsed", MinArgs: 0, MaxArgs: 256, Lower: lowerConsoleGroup}
	m["console.timeLog"] = BuiltinIntrinsic{Category: CategoryNodeGlobal, Name: "console.timeLog", MinArgs: 0, MaxArgs: 256, Lower: lowerConsoleTimeLog}
	m["console.trace"] = BuiltinIntrinsic{Category: CategoryNodeGlobal, Name: "console.trace", MinArgs: 0, MaxArgs: 256, Lower: lowerConsoleTrace}
	m["console.profile"] = BuiltinIntrinsic{Category: CategoryNodeGlobal, Name: "console.profile", MinArgs: 0, MaxArgs: 256, Lower: lowerConsoleNoop}
	m["console.profileEnd"] = BuiltinIntrinsic{Category: CategoryNodeGlobal, Name: "console.profileEnd", MinArgs: 0, MaxArgs: 256, Lower: lowerConsoleNoop}
	m["console.timeStamp"] = BuiltinIntrinsic{Category: CategoryNodeGlobal, Name: "console.timeStamp", MinArgs: 0, MaxArgs: 256, Lower: lowerConsoleNoop}

	registerCallIntrinsic(m, []string{"console.clear", "__console.clear"}, CategoryNodeGlobal, "__console.clear", nil, ir.TypeVoid, 0, 0)
	registerCallIntrinsic(m, []string{"console.groupEnd", "__console.groupEnd"}, CategoryNodeGlobal, "__console.groupEnd", nil, ir.TypeVoid, 0, 0)
	registerCallIntrinsic(m, []string{"console.count", "__console.count"}, CategoryNodeGlobal, "__console.count", []ir.Type{ir.TypeString}, ir.TypeVoid, 0, 1)
	registerCallIntrinsic(m, []string{"console.countReset", "__console.countReset"}, CategoryNodeGlobal, "__console.countReset", []ir.Type{ir.TypeString}, ir.TypeVoid, 0, 1)
	registerCallIntrinsic(m, []string{"console.time", "__console.time"}, CategoryNodeGlobal, "__console.time", []ir.Type{ir.TypeString}, ir.TypeVoid, 0, 1)
	registerCallIntrinsic(m, []string{"console.timeEnd", "__console.timeEnd"}, CategoryNodeGlobal, "__console.timeEnd", []ir.Type{ir.TypeString}, ir.TypeVoid, 0, 1)
	registerCallIntrinsic(m, []string{"process.exit", "__scriptgo.exit"}, CategoryNodeGlobal, "__process.exit", []ir.Type{ir.TypeNumber}, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"process.cwd", "__scriptgo.cwd"}, CategoryNodeGlobal, "__process.cwd", nil, ir.TypeString, 0, 0)
	registerCallIntrinsic(m, []string{"__scriptgo.argv"}, CategoryNodeGlobal, "__process.argv", nil, ir.TypeStringArray, 0, 0)
	registerCallIntrinsic(m, []string{"__scriptgo.pid"}, CategoryNodeGlobal, "__process.pid", nil, ir.TypeNumber, 0, 0)
	registerCallIntrinsic(m, []string{"__scriptgo.ppid"}, CategoryNodeGlobal, "__process.ppid", nil, ir.TypeNumber, 0, 0)
	registerCallIntrinsic(m, []string{"__scriptgo.version"}, CategoryNodeGlobal, "__process.version", nil, ir.TypeString, 0, 0)

	m["__scriptgo.readFileSync"] = BuiltinIntrinsic{
		Category: CategoryNodeModule,
		Name:     "__scriptgo.readFileSync",
		MinArgs:  1,
		MaxArgs:  2,
		Lower:    lowerFsReadFileSync,
	}
	registerCallIntrinsic(m, []string{"__scriptgo.writeFileSync"}, CategoryNodeModule, "__fs.writeFileSync", []ir.Type{ir.TypeString}, ir.TypeVoid, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.existsSync"}, CategoryNodeModule, "__fs.existsSync", []ir.Type{ir.TypeString}, ir.TypeBool, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.unlinkSync"}, CategoryNodeModule, "__fs.unlinkSync", []ir.Type{ir.TypeString}, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.readdirSync"}, CategoryNodeModule, "__fs.readdirSync", []ir.Type{ir.TypeString}, ir.TypeStringArray, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.copyFileSync"}, CategoryNodeModule, "__fs.copyFileSync", []ir.Type{ir.TypeString, ir.TypeString}, ir.TypeVoid, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.renameSync"}, CategoryNodeModule, "__fs.renameSync", []ir.Type{ir.TypeString, ir.TypeString}, ir.TypeVoid, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.appendFileSync"}, CategoryNodeModule, "__fs.appendFileSync", []ir.Type{ir.TypeString, ir.TypeString}, ir.TypeVoid, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.mkdirSync"}, CategoryNodeModule, "__fs.mkdirSync", []ir.Type{ir.TypeString, ir.TypeBool}, ir.TypeVoid, 1, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.rmSync"}, CategoryNodeModule, "__fs.rmSync", []ir.Type{ir.TypeString, ir.TypeBool, ir.TypeBool}, ir.TypeVoid, 1, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.statSync"}, CategoryNodeModule, "__fs.statSync", []ir.Type{ir.TypeString}, ir.Type("object:Stats"), 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.accessSync"}, CategoryNodeModule, "__fs.accessSync", []ir.Type{ir.TypeString, ir.TypeNumber}, ir.TypeBool, 1, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.chmodSync"}, CategoryNodeModule, "__fs.chmodSync", []ir.Type{ir.TypeString, ir.TypeNumber}, ir.TypeVoid, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.realpathSync"}, CategoryNodeModule, "__fs.realpathSync", []ir.Type{ir.TypeString}, ir.TypeString, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.truncateSync"}, CategoryNodeModule, "__fs.truncateSync", []ir.Type{ir.TypeString, ir.TypeNumber}, ir.TypeVoid, 1, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.mkdtempSync"}, CategoryNodeModule, "__fs.mkdtempSync", []ir.Type{ir.TypeString}, ir.TypeString, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.openSync"}, CategoryNodeModule, "__fs.openSync", []ir.Type{ir.TypeString, ir.TypeString, ir.TypeNumber}, ir.TypeNumber, 1, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.closeSync"}, CategoryNodeModule, "__fs.closeSync", []ir.Type{ir.TypeNumber}, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.readFdSync"}, CategoryNodeModule, "__fs.readFdSync", []ir.Type{ir.TypeNumber, ir.TypeBuffer, ir.TypeNumber, ir.TypeNumber, ir.TypeNumber}, ir.TypeNumber, 5, 5)
	registerCallIntrinsic(m, []string{"__scriptgo.writeFdSync"}, CategoryNodeModule, "__fs.writeFdSync", nil, ir.TypeNumber, 4, 4)
	registerCallIntrinsic(m, []string{"__scriptgo.opendirSync"}, CategoryNodeModule, "__fs.opendirSync", []ir.Type{ir.TypeString}, ir.TypeStringArray, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.fstatSync"}, CategoryNodeModule, "__fs.fstatSync", []ir.Type{ir.TypeNumber}, ir.Type("object:Stats"), 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.statfsSync"}, CategoryNodeModule, "__fs.statfsSync", []ir.Type{ir.TypeString}, ir.Type("object:StatFs"), 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.chownSync"}, CategoryNodeModule, "__fs.chownSync", []ir.Type{ir.TypeString, ir.TypeNumber, ir.TypeNumber}, ir.TypeVoid, 3, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.lchownSync"}, CategoryNodeModule, "__fs.lchownSync", []ir.Type{ir.TypeString, ir.TypeNumber, ir.TypeNumber}, ir.TypeVoid, 3, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.fchownSync"}, CategoryNodeModule, "__fs.fchownSync", []ir.Type{ir.TypeNumber, ir.TypeNumber, ir.TypeNumber}, ir.TypeVoid, 3, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.fchmodSync"}, CategoryNodeModule, "__fs.fchmodSync", []ir.Type{ir.TypeNumber, ir.TypeNumber}, ir.TypeVoid, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.linkSync"}, CategoryNodeModule, "__fs.linkSync", []ir.Type{ir.TypeString, ir.TypeString}, ir.TypeVoid, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.symlinkSync"}, CategoryNodeModule, "__fs.symlinkSync", []ir.Type{ir.TypeString, ir.TypeString}, ir.TypeVoid, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.readlinkSync"}, CategoryNodeModule, "__fs.readlinkSync", []ir.Type{ir.TypeString}, ir.TypeString, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.utimesSync"}, CategoryNodeModule, "__fs.utimesSync", []ir.Type{ir.TypeString, ir.TypeNumber, ir.TypeNumber}, ir.TypeVoid, 3, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.lutimesSync"}, CategoryNodeModule, "__fs.lutimesSync", []ir.Type{ir.TypeString, ir.TypeNumber, ir.TypeNumber}, ir.TypeVoid, 3, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.futimesSync"}, CategoryNodeModule, "__fs.futimesSync", []ir.Type{ir.TypeNumber, ir.TypeNumber, ir.TypeNumber}, ir.TypeVoid, 3, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.fsyncSync"}, CategoryNodeModule, "__fs.fsyncSync", []ir.Type{ir.TypeNumber}, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.fdatasyncSync"}, CategoryNodeModule, "__fs.fdatasyncSync", []ir.Type{ir.TypeNumber}, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.ftruncateSync"}, CategoryNodeModule, "__fs.ftruncateSync", []ir.Type{ir.TypeNumber, ir.TypeNumber}, ir.TypeVoid, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.rmdirSync"}, CategoryNodeModule, "__fs.rmdirSync", []ir.Type{ir.TypeString}, ir.TypeVoid, 1, 1)

	registerCallIntrinsic(m, []string{"crypto.randomUUID", "__scriptgo.randomUUID", "randomUUID"}, CategoryNodeModule, "__crypto.randomUUID", nil, ir.TypeString, 0, 0)
	registerCallIntrinsic(m, []string{"crypto.hashDigest", "__scriptgo.hashDigest", "hashDigest"}, CategoryNodeModule, "__crypto.hashDigest", []ir.Type{ir.TypeString, ir.TypeBuffer, ir.TypeUint8Array, ir.TypeUnknown, ir.TypeObject}, ir.TypeString, 2, 3)
	registerCallIntrinsic(m, []string{"crypto.hashDigestBuffer", "__scriptgo.hashDigestBuffer", "hashDigestBuffer"}, CategoryNodeModule, "__crypto.hashDigestBuffer", []ir.Type{ir.TypeString, ir.TypeBuffer, ir.TypeUint8Array, ir.TypeUnknown, ir.TypeObject}, ir.TypeString, 2, 3)
	registerCallIntrinsic(m, []string{"crypto.randomBytes", "__scriptgo.randomBytes", "randomBytes"}, CategoryNodeModule, "__crypto.randomBytes", []ir.Type{ir.TypeNumber}, ir.TypeBuffer, 1, 1)
	registerCallIntrinsic(m, []string{"crypto.randomInt", "__scriptgo.randomInt", "randomInt"}, CategoryNodeModule, "__crypto.randomInt", []ir.Type{ir.TypeNumber, ir.TypeNumber}, ir.TypeNumber, 2, 2)
	registerCustomIntrinsic(m, []string{"crypto.randomFill", "__scriptgo.randomFill", "randomFill"}, CategoryNodeModule, "__crypto.randomFill", ir.TypeBuffer, 1, 4, lowerRandomFill)
	registerCallIntrinsic(m, []string{"crypto.timingSafeEqual", "__scriptgo.timingSafeEqual", "timingSafeEqual"}, CategoryNodeModule, "__crypto.timingSafeEqual", []ir.Type{ir.TypeBuffer, ir.TypeBuffer}, ir.TypeBool, 2, 2)
	registerCallIntrinsic(m, []string{"crypto.hmacDigest", "__scriptgo.hmacDigest", "hmacDigest"}, CategoryNodeModule, "__crypto.hmacDigest", []ir.Type{ir.TypeString, ir.TypeString, ir.TypeString, ir.TypeString}, ir.TypeString, 3, 4)
	registerCallIntrinsic(m, []string{"crypto.hmacDigestBuffer", "__scriptgo.hmacDigestBuffer", "hmacDigestBuffer"}, CategoryNodeModule, "__crypto.hmacDigestBuffer", []ir.Type{ir.TypeString, ir.TypeBuffer, ir.TypeBuffer, ir.TypeString}, ir.TypeString, 3, 4)
	registerCallIntrinsic(m, []string{"crypto.pbkdf2Sync", "__scriptgo.pbkdf2Sync", "pbkdf2Sync"}, CategoryNodeModule, "__crypto.pbkdf2Sync", []ir.Type{ir.TypeString, ir.TypeString, ir.TypeNumber, ir.TypeNumber, ir.TypeString}, ir.TypeBuffer, 4, 5)
	registerCallIntrinsic(m, []string{"crypto.hkdfSync", "__scriptgo.hkdfSync", "hkdfSync"}, CategoryNodeModule, "__crypto.hkdfSync", []ir.Type{ir.TypeString, ir.TypeString, ir.TypeString, ir.TypeString, ir.TypeNumber}, ir.TypeArrayBuffer, 5, 5)
	registerCallIntrinsic(m, []string{"crypto.scryptSync", "__scriptgo.scryptSync", "scryptSync"}, CategoryNodeModule, "__crypto.scryptSync", []ir.Type{ir.TypeString, ir.TypeString, ir.TypeNumber}, ir.TypeBuffer, 3, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.cipherCreate"}, CategoryNodeModule, "__crypto.cipherCreate", nil, ir.TypePointer, 4, 4)
	registerCallIntrinsic(m, []string{"__scriptgo.cipherUpdate"}, CategoryNodeModule, "__crypto.cipherUpdate", nil, ir.TypeBuffer, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.cipherFinal"}, CategoryNodeModule, "__crypto.cipherFinal", nil, ir.TypeBuffer, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.cipherSetAAD"}, CategoryNodeModule, "__crypto.cipherSetAAD", nil, ir.TypeVoid, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.cipherGetTag"}, CategoryNodeModule, "__crypto.cipherGetTag", nil, ir.TypeBuffer, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.cipherSetTag"}, CategoryNodeModule, "__crypto.cipherSetTag", nil, ir.TypeVoid, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.cipherSetAutoPadding"}, CategoryNodeModule, "__crypto.cipherSetAutoPadding", nil, ir.TypeVoid, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.cipherDestroy"}, CategoryNodeModule, "__crypto.cipherDestroy", nil, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.getCipherInfo"}, CategoryNodeModule, "__crypto.getCipherInfo", nil, ir.TypeString, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.cryptoSign"}, CategoryNodeModule, "__crypto.sign", nil, ir.TypeBuffer, 3, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.cryptoVerify"}, CategoryNodeModule, "__crypto.verify", nil, ir.TypeBool, 4, 4)
	registerCallIntrinsic(m, []string{"__scriptgo.publicEncrypt"}, CategoryNodeModule, "__crypto.publicEncrypt", nil, ir.TypeBuffer, 3, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.publicDecrypt"}, CategoryNodeModule, "__crypto.publicDecrypt", nil, ir.TypeBuffer, 3, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.privateEncrypt"}, CategoryNodeModule, "__crypto.privateEncrypt", nil, ir.TypeBuffer, 3, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.privateDecrypt"}, CategoryNodeModule, "__crypto.privateDecrypt", nil, ir.TypeBuffer, 3, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.generateKeyPairSync"}, CategoryNodeModule, "__crypto.generateKeyPairSync", nil, ir.TypeString, 3, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.keyDetails"}, CategoryNodeModule, "__crypto.keyDetails", nil, ir.TypeString, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.dhCreate"}, CategoryNodeModule, "__crypto.dhCreate", nil, ir.TypePointer, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.dhCreateGroup"}, CategoryNodeModule, "__crypto.dhCreateGroup", nil, ir.TypePointer, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.dhGenerateKeys"}, CategoryNodeModule, "__crypto.dhGenerateKeys", nil, ir.TypeBuffer, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.dhComputeSecret"}, CategoryNodeModule, "__crypto.dhComputeSecret", nil, ir.TypeBuffer, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.dhGetKey"}, CategoryNodeModule, "__crypto.dhGetKey", nil, ir.TypeBuffer, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.dhSetKey"}, CategoryNodeModule, "__crypto.dhSetKey", nil, ir.TypeVoid, 3, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.dhDestroy"}, CategoryNodeModule, "__crypto.dhDestroy", nil, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.ecdhCreate"}, CategoryNodeModule, "__crypto.ecdhCreate", nil, ir.TypePointer, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.ecdhGenerateKeys"}, CategoryNodeModule, "__crypto.ecdhGenerateKeys", nil, ir.TypeBuffer, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.ecdhComputeSecret"}, CategoryNodeModule, "__crypto.ecdhComputeSecret", nil, ir.TypeBuffer, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.ecdhGetKey"}, CategoryNodeModule, "__crypto.ecdhGetKey", nil, ir.TypeBuffer, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.ecdhSetKey"}, CategoryNodeModule, "__crypto.ecdhSetKey", nil, ir.TypeVoid, 3, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.ecdhDestroy"}, CategoryNodeModule, "__crypto.ecdhDestroy", nil, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.spkacVerify"}, CategoryNodeModule, "__crypto.spkacVerify", nil, ir.TypeBool, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.spkacExportChallenge"}, CategoryNodeModule, "__crypto.spkacExportChallenge", nil, ir.TypeString, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.spkacExportPublicKey"}, CategoryNodeModule, "__crypto.spkacExportPublicKey", nil, ir.TypeString, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.x509CheckPrivateKey"}, CategoryNodeModule, "__crypto.x509CheckPrivateKey", nil, ir.TypeBool, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.x509Verify"}, CategoryNodeModule, "__crypto.x509Verify", nil, ir.TypeBool, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.getFips"}, CategoryNodeModule, "__crypto.getFips", nil, ir.TypeNumber, 0, 0)
	registerCallIntrinsic(m, []string{"__scriptgo.setFips"}, CategoryNodeModule, "__crypto.setFips", nil, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.secureHeapUsed"}, CategoryNodeModule, "__crypto.secureHeapUsed", nil, ir.TypeString, 0, 0)
	registerCallIntrinsic(m, []string{"__scriptgo.setEngine"}, CategoryNodeModule, "__crypto.setEngine", nil, ir.TypeVoid, 1, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.zlibTransformString", "zlibTransformString"}, CategoryNodeModule, "__zlib.transform_string", []ir.Type{ir.TypeString, ir.TypeNumber}, ir.TypeUint8Array, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.zlibTransformBuffer", "zlibTransformBuffer"}, CategoryNodeModule, "__zlib.transform_buffer", []ir.Type{ir.TypeUint8Array, ir.TypeNumber}, ir.TypeUint8Array, 2, 2)
	registerCallIntrinsic(m, []string{"os.platform", "__scriptgo.platform", "platform"}, CategoryNodeModule, "__os.platform", nil, ir.TypeString, 0, 0)
	registerCallIntrinsic(m, []string{"os.arch", "__scriptgo.arch", "arch"}, CategoryNodeModule, "__os.arch", nil, ir.TypeString, 0, 0)
	registerCallIntrinsic(m, []string{"os.homedir", "__scriptgo.homedir", "homedir"}, CategoryNodeModule, "__os.homedir", nil, ir.TypeString, 0, 0)
	registerCallIntrinsic(m, []string{"os.uptime", "__scriptgo.uptime", "uptime"}, CategoryNodeModule, "__os.uptime", nil, ir.TypeNumber, 0, 0)
	registerCallIntrinsic(m, []string{"os.totalmem", "__scriptgo.totalmem", "totalmem"}, CategoryNodeModule, "__os.totalmem", nil, ir.TypeNumber, 0, 0)
	registerCallIntrinsic(m, []string{"os.freemem", "__scriptgo.freemem", "freemem"}, CategoryNodeModule, "__os.freemem", nil, ir.TypeNumber, 0, 0)
	registerCallIntrinsic(m, []string{"os.type", "__scriptgo.type", "type"}, CategoryNodeModule, "__os.type", nil, ir.TypeString, 0, 0)
	registerCallIntrinsic(m, []string{"os.release", "__scriptgo.release", "release"}, CategoryNodeModule, "__os.release", nil, ir.TypeString, 0, 0)
	registerCallIntrinsic(m, []string{"os.tmpdir", "__scriptgo.tmpdir", "tmpdir"}, CategoryNodeModule, "__os.tmpdir", nil, ir.TypeString, 0, 0)
	registerCallIntrinsic(m, []string{"os.availableParallelism", "__scriptgo.availableParallelism", "availableParallelism"}, CategoryNodeModule, "__os.available_parallelism", nil, ir.TypeNumber, 0, 0)
	registerCallIntrinsic(m, []string{"os.hostname", "__scriptgo.hostname", "hostname"}, CategoryNodeModule, "__os.hostname", nil, ir.TypeString, 0, 0)
	registerCallIntrinsic(m, []string{"__scriptgo.loadavg"}, CategoryNodeModule, "__os.loadavg", nil, ir.TypeString, 0, 0)
	registerCallIntrinsic(m, []string{"__scriptgo.cpus"}, CategoryNodeModule, "__os.cpus", nil, ir.TypeString, 0, 0)
	registerCallIntrinsic(m, []string{"__scriptgo.networkInterfaces"}, CategoryNodeModule, "__os.network_interfaces", nil, ir.TypeString, 0, 0)
	registerCallIntrinsic(m, []string{"__scriptgo.userInfo"}, CategoryNodeModule, "__os.user_info", nil, ir.TypeString, 0, 0)
	registerCallIntrinsic(m, []string{"os.machine", "__scriptgo.machine", "machine"}, CategoryNodeModule, "__os.machine", nil, ir.TypeString, 0, 0)
	registerCallIntrinsic(m, []string{"os.version", "__scriptgo.version", "version"}, CategoryNodeModule, "__os.version", nil, ir.TypeString, 0, 0)
	registerCallIntrinsic(m, []string{"__scriptgo.getPriority"}, CategoryNodeModule, "__os.get_priority", []ir.Type{ir.TypeNumber}, ir.TypeNumber, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.setPriority"}, CategoryNodeModule, "__os.set_priority", []ir.Type{ir.TypeNumber, ir.TypeNumber}, ir.TypeVoid, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.execSync"}, CategoryNodeModule, "__child_process.execSync", []ir.Type{ir.TypeString, ir.TypeString, ir.TypeString}, ir.TypeString, 1, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.spawnSync"}, CategoryNodeModule, "__child_process.spawnSync", []ir.Type{ir.TypeString, ir.TypeStringArray, ir.TypeString, ir.TypeString}, ir.Type("object:SpawnSyncReturns"), 1, 4)
	registerCallIntrinsic(m, []string{"__scriptgo.childProcessSpawnAsync"}, CategoryNodeModule, "__child_process.spawnAsync", []ir.Type{ir.TypeString, ir.TypeStringArray, ir.TypeString}, ir.Type("object:ChildProcessSpawnResult"), 1, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.childProcessPollStatus"}, CategoryNodeModule, "__child_process.pollStatus", []ir.Type{ir.TypeNumber}, ir.Type("object:ChildProcessPollResult"), 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.childProcessPipeRead"}, CategoryNodeModule, "__child_process.pipeRead", []ir.Type{ir.TypeNumber, ir.TypeNumber}, ir.Type("object:ChildProcessReadResult"), 1, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.childProcessPipeWrite"}, CategoryNodeModule, "__child_process.pipeWrite", []ir.Type{ir.TypeNumber, ir.TypeString, ir.TypeNumber}, ir.TypeNumber, 3, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.childProcessPipeClose"}, CategoryNodeModule, "__child_process.pipeClose", []ir.Type{ir.TypeNumber}, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.childProcessKill"}, CategoryNodeModule, "__child_process.kill", []ir.Type{ir.TypeNumber, ir.TypeNumber}, ir.TypeBool, 1, 2)

	registerCallIntrinsic(m, []string{"__scriptgo.fsWatchCreate"}, CategoryNodeModule, "__fs.watchCreate", []ir.Type{ir.TypeString}, ir.TypeNumber, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.fsWatchPoll"}, CategoryNodeModule, "__fs.watchPoll", []ir.Type{ir.TypeNumber}, ir.Type("object:FSWatchPollResult"), 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.fsWatchClose"}, CategoryNodeModule, "__fs.watchClose", []ir.Type{ir.TypeNumber}, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.fetchSync"}, CategoryNodeModule, "__http.fetchSync", []ir.Type{ir.TypeString, ir.TypeString, ir.TypeStringArray, ir.TypeString}, ir.Type("object:FetchResponseData"), 1, 4)
	registerCallIntrinsic(m, []string{"__scriptgo.websocketConnect"}, CategoryWebCompat, "__websocket.connect", []ir.Type{ir.TypeString, ir.TypeString}, ir.TypeNumber, 1, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.websocketSendText"}, CategoryWebCompat, "__websocket.sendText", []ir.Type{ir.TypeNumber, ir.TypeString}, ir.TypeNumber, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.websocketClose"}, CategoryWebCompat, "__websocket.close", []ir.Type{ir.TypeNumber, ir.TypeNumber, ir.TypeString}, ir.TypeVoid, 1, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.websocketPoll"}, CategoryWebCompat, "__websocket.poll", []ir.Type{ir.TypeNumber}, ir.Type("object:WebSocketPollData"), 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.websocketReadyState"}, CategoryWebCompat, "__websocket.readyState", []ir.Type{ir.TypeNumber}, ir.TypeNumber, 1, 1)
	registerCallIntrinsic(m, []string{"__stream.getDefaultHighWaterMark", "__scriptgo.streamGetDefaultHighWaterMark"}, CategoryNodeModule, "__stream.getDefaultHighWaterMark", []ir.Type{ir.TypeBool}, ir.TypeNumber, 0, 1)
	registerCallIntrinsic(m, []string{"__stream.setDefaultHighWaterMark", "__scriptgo.streamSetDefaultHighWaterMark"}, CategoryNodeModule, "__stream.setDefaultHighWaterMark", []ir.Type{ir.TypeBool, ir.TypeNumber}, ir.TypeVoid, 2, 2)

	registerCallIntrinsic(m, []string{"__scriptgo.sqliteOpen"}, CategoryNodeModule, "__sqlite.open", nil, ir.TypeObject, 1, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteClose"}, CategoryNodeModule, "__sqlite.close", nil, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteExec"}, CategoryNodeModule, "__sqlite.exec", nil, ir.TypeVoid, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.sqlitePrepare"}, CategoryNodeModule, "__sqlite.prepare", nil, ir.TypeObject, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteRun"}, CategoryNodeModule, "__sqlite.run", nil, ir.Type("object:StatementResult"), 1, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteGet"}, CategoryNodeModule, "__sqlite.get", nil, ir.TypeObject, 1, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteAll"}, CategoryNodeModule, "__sqlite.all", nil, ir.TypeUnknownArray, 1, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteColumns"}, CategoryNodeModule, "__sqlite.columns", nil, ir.TypeUnknownArray, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteExpandedSQL"}, CategoryNodeModule, "__sqlite.expandedSQL", nil, ir.TypeString, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteFinalize"}, CategoryNodeModule, "__sqlite.finalize", nil, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteStmtConfig"}, CategoryNodeModule, "__sqlite.stmtConfig", nil, ir.TypeVoid, 5, 5)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteEnableLoadExtension"}, CategoryNodeModule, "__sqlite.enableLoadExtension", nil, ir.TypeVoid, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteLoadExtension"}, CategoryNodeModule, "__sqlite.loadExtension", nil, ir.TypeVoid, 2, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteCreateSession"}, CategoryNodeModule, "__sqlite.createSession", nil, ir.TypeObject, 1, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteSessionChangeset"}, CategoryNodeModule, "__sqlite.sessionChangeset", nil, ir.TypeUint8Array, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteSessionPatchset"}, CategoryNodeModule, "__sqlite.sessionPatchset", nil, ir.TypeUint8Array, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteSessionClose"}, CategoryNodeModule, "__sqlite.sessionClose", nil, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteApplyChangeset"}, CategoryNodeModule, "__sqlite.applyChangeset", nil, ir.TypeBool, 2, 3)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteLocation"}, CategoryNodeModule, "__sqlite.location", nil, ir.TypeString, 1, 2)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteIsTransaction"}, CategoryNodeModule, "__sqlite.isTransaction", nil, ir.TypeBool, 1, 1)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteCreateFunction"}, CategoryNodeModule, "__sqlite.createFunction", nil, ir.TypeVoid, 4, 5)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteCreateAggregate"}, CategoryNodeModule, "__sqlite.createAggregate", nil, ir.TypeVoid, 4, 5)
	registerCallIntrinsic(m, []string{"__scriptgo.sqliteBackup"}, CategoryNodeModule, "__sqlite.backup", nil, ir.TypeNumber, 2, 2)
}

func registerWebTimerIntrinsics(m map[string]BuiltinIntrinsic) {
	// Web-compatible & Timer globals (Category 2: WebCompat & NodeGlobal)
	registerCallIntrinsic(m, []string{"btoa", "__scriptgo.btoa", "buffer.btoa"}, CategoryWebCompat, "__web.btoa", []ir.Type{ir.TypeString}, ir.TypeString, 1, 1)
	registerCallIntrinsic(m, []string{"atob", "__scriptgo.atob", "buffer.atob"}, CategoryWebCompat, "__web.atob", []ir.Type{ir.TypeString}, ir.TypeString, 1, 1)
	registerCallIntrinsic(m, []string{"performance.now"}, CategoryWebCompat, "__performance.now", nil, ir.TypeNumber, 0, 0)
	registerCallIntrinsic(m, []string{"queueMicrotask"}, CategoryWebCompat, "__async.queueMicrotask", []ir.Type{ir.TypeClosure}, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"Promise.resolve"}, CategoryECMAScript, "__async.promise_resolve", []ir.Type{ir.TypeNumber}, ir.Type("object:Promise"), 1, 1)
	registerCallIntrinsic(m, []string{"Promise.all"}, CategoryECMAScript, "__async.promise_all", []ir.Type{ir.TypeObject}, ir.Type("object:Promise"), 1, 1)
	registerCallIntrinsic(m, []string{"setTimeout", "__scriptgo.setTimeout", "timers.setTimeout"}, CategoryWebCompat, "__timers.setTimeout", []ir.Type{ir.TypeClosure, ir.TypeNumber, ir.TypeUnknownArray}, ir.TypeNumber, 1, 3)
	registerCallIntrinsic(m, []string{"clearTimeout", "__scriptgo.clearTimeout", "timers.clearTimeout"}, CategoryWebCompat, "__timers.clearTimeout", []ir.Type{ir.TypeNumber}, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"setInterval", "__scriptgo.setInterval", "timers.setInterval"}, CategoryWebCompat, "__timers.setInterval", []ir.Type{ir.TypeClosure, ir.TypeNumber, ir.TypeUnknownArray}, ir.TypeNumber, 1, 3)
	registerCallIntrinsic(m, []string{"clearInterval", "__scriptgo.clearInterval", "timers.clearInterval"}, CategoryWebCompat, "__timers.clearInterval", []ir.Type{ir.TypeNumber}, ir.TypeVoid, 1, 1)
	registerCallIntrinsic(m, []string{"setImmediate", "__scriptgo.setImmediate", "timers.setImmediate"}, CategoryWebCompat, "__timers.setImmediate", []ir.Type{ir.TypeClosure, ir.TypeUnknownArray}, ir.TypeNumber, 1, 2)
	registerCallIntrinsic(m, []string{"clearImmediate", "__scriptgo.clearImmediate", "timers.clearImmediate"}, CategoryWebCompat, "__timers.clearImmediate", []ir.Type{ir.TypeNumber}, ir.TypeVoid, 1, 1)
}
