package llvm

// Native runtime ABI declarations, emitted verbatim in module order by
// writeRuntimeDeclarations. Keep each block in sync with internal/runtime.

const declarationsCrypto = `declare i32 @scriptgo_crypto_random_uuid(ptr)
declare i32 @scriptgo_crypto_hash_digest(ptr, ptr, ptr, ptr)
declare i32 @scriptgo_crypto_hash_digest_buffer(ptr, ptr, ptr, ptr)
declare i32 @scriptgo_crypto_random_bytes(double, ptr)
declare i32 @scriptgo_crypto_random_int(double, double, ptr)
declare i32 @scriptgo_crypto_random_fill(ptr, double, double, ptr)
declare i32 @scriptgo_crypto_timing_safe_equal(ptr, ptr, ptr)
declare i32 @scriptgo_crypto_hmac_digest(ptr, ptr, ptr, ptr, ptr)
declare i32 @scriptgo_crypto_hmac_digest_buffer(ptr, ptr, ptr, ptr, ptr)
declare i32 @scriptgo_crypto_pbkdf2_sync(ptr, ptr, double, double, ptr, ptr)

declare i32 @scriptgo_crypto_hkdf_sync(ptr, ptr, ptr, ptr, double, ptr)

declare i32 @scriptgo_crypto_scrypt_sync(ptr, ptr, double, ptr)

declare i32 @scriptgo_crypto_cipher_create(ptr, ptr, ptr, double, ptr)
declare i32 @scriptgo_crypto_cipher_update(ptr, ptr, ptr)
declare i32 @scriptgo_crypto_cipher_final(ptr, ptr)
declare i32 @scriptgo_crypto_cipher_set_aad(ptr, ptr)
declare i32 @scriptgo_crypto_cipher_get_tag(ptr, ptr)
declare i32 @scriptgo_crypto_cipher_set_tag(ptr, ptr)
declare i32 @scriptgo_crypto_cipher_set_auto_padding(ptr, double)
declare i32 @scriptgo_crypto_cipher_destroy(ptr)
declare i32 @scriptgo_crypto_get_cipher_info(ptr, ptr)
declare i32 @scriptgo_crypto_sign(ptr, ptr, ptr, ptr)
declare i32 @scriptgo_crypto_verify(ptr, ptr, ptr, ptr, ptr)
declare i32 @scriptgo_crypto_public_encrypt(ptr, ptr, double, ptr)
declare i32 @scriptgo_crypto_public_decrypt(ptr, ptr, double, ptr)
declare i32 @scriptgo_crypto_private_encrypt(ptr, ptr, double, ptr)
declare i32 @scriptgo_crypto_private_decrypt(ptr, ptr, double, ptr)
declare i32 @scriptgo_crypto_generate_key_pair_sync(ptr, double, ptr, ptr)
declare i32 @scriptgo_crypto_key_details(ptr, ptr)
declare i32 @scriptgo_crypto_dh_create(ptr, ptr, ptr)
declare i32 @scriptgo_crypto_dh_create_group(ptr, ptr)
declare i32 @scriptgo_crypto_dh_generate_keys(ptr, ptr)
declare i32 @scriptgo_crypto_dh_compute_secret(ptr, ptr, ptr)
declare i32 @scriptgo_crypto_dh_get_key(ptr, double, ptr)
declare i32 @scriptgo_crypto_dh_set_key(ptr, double, ptr)
declare i32 @scriptgo_crypto_dh_destroy(ptr)
declare i32 @scriptgo_crypto_ecdh_create(ptr, ptr)
declare i32 @scriptgo_crypto_ecdh_generate_keys(ptr, ptr)
declare i32 @scriptgo_crypto_ecdh_compute_secret(ptr, ptr, ptr)
declare i32 @scriptgo_crypto_ecdh_get_key(ptr, double, ptr)
declare i32 @scriptgo_crypto_ecdh_set_key(ptr, double, ptr)
declare i32 @scriptgo_crypto_ecdh_destroy(ptr)
declare i32 @scriptgo_crypto_spkac_verify(ptr, ptr)
declare i32 @scriptgo_crypto_spkac_export_challenge(ptr, ptr)
declare i32 @scriptgo_crypto_spkac_export_public_key(ptr, ptr)
declare i32 @scriptgo_crypto_x509_check_private_key(ptr, ptr, ptr)
declare i32 @scriptgo_crypto_x509_verify(ptr, ptr, ptr)
declare i32 @scriptgo_crypto_get_fips(ptr)
declare i32 @scriptgo_crypto_set_fips(double)
declare i32 @scriptgo_crypto_secure_heap_used(ptr)
declare i32 @scriptgo_crypto_set_engine(ptr, double)

`

const declarationsZlib = `declare i32 @scriptgo_zlib_transform_string(ptr, double, ptr)
declare i32 @scriptgo_zlib_transform_buffer(ptr, double, ptr)

`

const declarationsDate = `declare i32 @scriptgo_date_now(ptr)
declare i32 @scriptgo_date_to_iso_string(double, ptr)
declare i32 @scriptgo_date_to_string(double, ptr)
declare i32 @scriptgo_date_to_date_string(double, ptr)
declare i32 @scriptgo_date_to_time_string(double, ptr)
declare i32 @scriptgo_date_to_utc_string(double, ptr)
declare i32 @scriptgo_date_parse(ptr, ptr)
declare i32 @scriptgo_date_utc(double, double, double, double, double, double, double, ptr)
declare i32 @scriptgo_date_get_date(double, ptr)
declare i32 @scriptgo_date_get_day(double, ptr)
declare i32 @scriptgo_date_get_full_year(double, ptr)
declare i32 @scriptgo_date_get_hours(double, ptr)
declare i32 @scriptgo_date_get_milliseconds(double, ptr)
declare i32 @scriptgo_date_get_minutes(double, ptr)
declare i32 @scriptgo_date_get_month(double, ptr)
declare i32 @scriptgo_date_get_seconds(double, ptr)
declare i32 @scriptgo_date_get_timezone_offset(double, ptr)
declare i32 @scriptgo_date_get_utc_date(double, ptr)
declare i32 @scriptgo_date_get_utc_day(double, ptr)
declare i32 @scriptgo_date_get_utc_full_year(double, ptr)
declare i32 @scriptgo_date_get_utc_hours(double, ptr)
declare i32 @scriptgo_date_get_utc_milliseconds(double, ptr)
declare i32 @scriptgo_date_get_utc_minutes(double, ptr)
declare i32 @scriptgo_date_get_utc_month(double, ptr)
declare i32 @scriptgo_date_get_utc_seconds(double, ptr)
declare i32 @scriptgo_date_set_date(double, double, ptr)
declare i32 @scriptgo_date_set_full_year(double, double, ptr)
declare i32 @scriptgo_date_set_hours(double, double, ptr)
declare i32 @scriptgo_date_set_milliseconds(double, double, ptr)
declare i32 @scriptgo_date_set_minutes(double, double, ptr)
declare i32 @scriptgo_date_set_month(double, double, ptr)
declare i32 @scriptgo_date_set_seconds(double, double, ptr)
declare i32 @scriptgo_date_set_utc_date(double, double, ptr)
declare i32 @scriptgo_date_set_utc_full_year(double, double, ptr)
declare i32 @scriptgo_date_set_utc_hours(double, double, ptr)
declare i32 @scriptgo_date_set_utc_milliseconds(double, double, ptr)
declare i32 @scriptgo_date_set_utc_minutes(double, double, ptr)
declare i32 @scriptgo_date_set_utc_month(double, double, ptr)
declare i32 @scriptgo_date_set_utc_seconds(double, double, ptr)

`

const declarationsWeb = `declare i32 @scriptgo_web_btoa(ptr, ptr)
declare i32 @scriptgo_web_atob(ptr, ptr)
declare i32 @scriptgo_performance_now(ptr)
declare i32 @scriptgo_fetch_sync(ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare i32 @scriptgo_stream_get_default_high_water_mark(i32, ptr)
declare i32 @scriptgo_stream_set_default_high_water_mark(i32, double)

`

const declarationsSqlite = `declare i32 @scriptgo_sqlite_open(ptr, double, ptr)
declare i32 @scriptgo_sqlite_close(ptr)
declare i32 @scriptgo_sqlite_exec(ptr, ptr)
declare i32 @scriptgo_sqlite_prepare(ptr, ptr, ptr)
declare i32 @scriptgo_sqlite_run(ptr, ptr, ptr, ptr)
declare i32 @scriptgo_sqlite_get(ptr, ptr, ptr, ptr)
declare i32 @scriptgo_sqlite_all(ptr, ptr, ptr, ptr)
declare i32 @scriptgo_sqlite_columns(ptr, ptr)
declare i32 @scriptgo_sqlite_expanded_sql(ptr, ptr)
declare i32 @scriptgo_sqlite_finalize(ptr)
declare i32 @scriptgo_sqlite_stmt_config(ptr, double, double, double, double)
declare i32 @scriptgo_sqlite_enable_load_extension(ptr, double)
declare i32 @scriptgo_sqlite_load_extension(ptr, ptr)
declare i32 @scriptgo_sqlite_session_create(ptr, ptr, ptr)
declare i32 @scriptgo_sqlite_session_changeset(ptr, ptr)
declare i32 @scriptgo_sqlite_session_patchset(ptr, ptr)
declare i32 @scriptgo_sqlite_session_close(ptr)
declare i32 @scriptgo_sqlite_apply_changeset(ptr, ptr, double, ptr)
declare i32 @scriptgo_sqlite_location(ptr, ptr, ptr)
declare i32 @scriptgo_sqlite_is_transaction(ptr, ptr)
declare i32 @scriptgo_sqlite_create_function(ptr, ptr, double, double, ptr)
declare i32 @scriptgo_sqlite_create_aggregate(ptr, ptr, double, double, ptr)
declare i32 @scriptgo_sqlite_backup(ptr, ptr, ptr)

`

const declarationsException = `declare void @scriptgo_exception_push(ptr)
declare void @scriptgo_exception_pop(ptr)
declare ptr @scriptgo_exception_buf(ptr)
declare ptr @scriptgo_exception_frame_new()
declare void @scriptgo_exception_frame_free(ptr)
declare i32 @setjmp(ptr) returns_twice
declare void @scriptgo_throw_string(ptr)
declare void @scriptgo_throw_number(double)
declare void @scriptgo_throw_bool(i32)
declare void @scriptgo_exception_throw_copy(ptr)
declare ptr @scriptgo_exception_get_string(ptr)
declare double @scriptgo_exception_get_number(ptr)
declare i32 @scriptgo_exception_get_bool(ptr)
declare void @scriptgo_exception_rethrow(ptr)

`

const declarationsClosure = `declare i32 @scriptgo_closure_create(ptr, ptr, ptr, i32, ptr)
declare i32 @scriptgo_closure_invoke_value(ptr, i32, ptr, ptr, ptr, ptr, ptr)
declare i32 @scriptgo_array_get_unknown(ptr, double, ptr)
declare i32 @scriptgo_array_map_number(ptr, ptr, ptr)
declare i32 @scriptgo_array_flat_map_number(ptr, ptr, ptr)
declare i32 @scriptgo_array_flat_map_number_scalar(ptr, ptr, ptr)
declare i32 @scriptgo_array_map_number_from_ptr(ptr, ptr, ptr)
declare i32 @scriptgo_array_map_number_from_string(ptr, ptr, ptr)
declare i32 @scriptgo_array_map_string(ptr, ptr, ptr)
declare i32 @scriptgo_array_map_string_from_number(ptr, ptr, ptr)
declare i32 @scriptgo_array_map_string_from_ptr(ptr, ptr, ptr)
declare i32 @scriptgo_array_map_ptr(ptr, ptr, ptr)
declare i32 @scriptgo_array_map_ptr_from_number(ptr, ptr, ptr)
declare i32 @scriptgo_array_map_ptr_from_string(ptr, ptr, ptr)
declare i32 @scriptgo_array_filter_number(ptr, ptr, ptr)
declare i32 @scriptgo_array_filter_string(ptr, ptr, ptr)
declare i32 @scriptgo_array_filter_ptr(ptr, ptr, ptr)
declare i32 @scriptgo_array_for_each_number(ptr, ptr)
declare i32 @scriptgo_array_for_each_string(ptr, ptr)
declare i32 @scriptgo_array_for_each_ptr(ptr, ptr)
declare i32 @scriptgo_array_reduce_number(ptr, ptr, double, ptr)
declare i32 @scriptgo_array_reduce_number_seeded_left(ptr, ptr, ptr)
declare i32 @scriptgo_array_find_number(ptr, ptr, ptr)
declare i32 @scriptgo_array_find_index_number(ptr, ptr, ptr)
declare i32 @scriptgo_array_find_index_string(ptr, ptr, ptr)
declare i32 @scriptgo_array_some_number(ptr, ptr, ptr)
declare i32 @scriptgo_array_every_number(ptr, ptr, ptr)
declare i32 @scriptgo_array_fill_number(ptr, double, double, double, i32, i32, ptr)
declare i32 @scriptgo_array_fill_string(ptr, ptr, double, double, i32, i32, ptr)
declare i32 @scriptgo_array_to_reversed(ptr, ptr)
declare i32 @scriptgo_array_to_sorted_number(ptr, ptr)
declare i32 @scriptgo_array_to_sorted_string(ptr, ptr)
declare i32 @scriptgo_array_find_last_number(ptr, ptr, ptr)
declare i32 @scriptgo_array_find_last_index_number(ptr, ptr, ptr)
declare i32 @scriptgo_array_find_last_index_string(ptr, ptr, ptr)
declare i32 @scriptgo_array_reduce_right_number(ptr, ptr, double, ptr)
declare i32 @scriptgo_array_reduce_number_seeded_right(ptr, ptr, ptr)
declare i32 @scriptgo_array_last_index_of_number(ptr, double, double, ptr)
declare i32 @scriptgo_array_last_index_of_string(ptr, ptr, double, ptr)
declare i32 @scriptgo_array_copy_within(ptr, double, double, double, i32, i32, ptr)
declare i32 @scriptgo_array_with_number(ptr, double, double, ptr)
declare i32 @scriptgo_array_with_string(ptr, double, ptr, ptr)
declare i32 @scriptgo_array_to_spliced(ptr, double, double, i32, ptr)
declare i32 @scriptgo_array_sort_number(ptr, ptr)
declare i32 @scriptgo_array_sort_string(ptr, ptr)
declare i32 @scriptgo_array_sort_closure_number(ptr, ptr, ptr)
declare i32 @scriptgo_array_sort_closure_string(ptr, ptr, ptr)
declare i32 @scriptgo_array_sort_closure_ptr(ptr, ptr, ptr)
declare i32 @scriptgo_array_is_array(ptr, ptr)
declare i32 @scriptgo_queue_microtask(ptr, ptr)
declare i32 @scriptgo_promise_create(ptr)
declare i32 @scriptgo_promise_resolver_create(ptr, i32, ptr)
declare i32 @scriptgo_promise_construct(ptr, ptr)
declare i32 @scriptgo_promise_resolve(ptr, ptr)
declare i32 @scriptgo_promise_resolve_existing_array(ptr, ptr)
declare i32 @scriptgo_promise_resolve_number(ptr, double)
declare i32 @scriptgo_promise_resolve_bool(ptr, i32)
declare i32 @scriptgo_promise_resolve_bigint(ptr, i64)
declare i32 @scriptgo_promise_resolve_boxed(ptr, i32, i64)
declare i32 @scriptgo_promise_reject(ptr, ptr)
declare i32 @scriptgo_promise_reject_boxed(ptr, i32, i64)
declare i32 @scriptgo_promise_then(ptr, ptr, ptr, i32, ptr)
declare i32 @scriptgo_promise_schedule_resume(ptr, ptr)
declare i32 @scriptgo_promise_schedule_resume_pair(ptr, ptr, ptr)
declare i32 @scriptgo_promise_resolve_unknown(i32, i64, ptr)
declare i32 @scriptgo_promise_resolve_existing(ptr, ptr)
declare i32 @scriptgo_promise_reject_existing(ptr, ptr)
declare i32 @scriptgo_promise_resolve_existing_number(ptr, double)
declare i32 @scriptgo_promise_resolve_existing_bool(ptr, i32)
declare i32 @scriptgo_promise_resolve_existing_boxed(ptr, i32, i64)
declare i32 @scriptgo_promise_reject_existing_boxed(ptr, i32, i64)
declare i32 @scriptgo_promise_all_numbers(ptr, ptr)
declare i32 @scriptgo_async_frame_new(i64, ptr)
declare i32 @scriptgo_async_frame_set(ptr, i64, ptr)
declare i32 @scriptgo_async_frame_get(ptr, i64, ptr)
declare i32 @scriptgo_async_frame_release(ptr)
declare i32 @scriptgo_promise_await_number(ptr, ptr)
declare i32 @scriptgo_promise_await_ptr(ptr, ptr)
declare i32 @scriptgo_promise_await_bool(ptr, ptr)
declare i32 @scriptgo_promise_await_bigint(ptr, ptr)
declare i32 @scriptgo_promise_await_boxed(ptr, ptr, ptr)
declare i32 @scriptgo_promise_await_unknown(i32, i64, ptr, ptr)
declare i32 @scriptgo_event_loop_run()
declare i32 @scriptgo_timer_set_timeout(ptr, double, ptr)
declare i32 @scriptgo_timer_clear_timeout(double)
declare i32 @scriptgo_timer_set_interval(ptr, double, ptr)
declare i32 @scriptgo_timer_clear_interval(double)
declare i32 @scriptgo_timer_set_immediate(ptr, ptr)
declare i32 @scriptgo_timer_clear_immediate(double)
declare i32 @scriptgo_timers_drain()

`

const declarationsArraybuffer = `declare i32 @scriptgo_arraybuffer_new(i64, ptr)
declare i32 @scriptgo_arraybuffer_slice(ptr, double, double, ptr)
declare i32 @scriptgo_arraybuffer_byte_length(ptr, ptr)
declare i32 @scriptgo_arraybuffer_is_view(ptr, ptr)
declare i32 @scriptgo_arraybuffer_view_byte_length(ptr, ptr)
declare i32 @scriptgo_arraybuffer_view_byte_offset(ptr, ptr)
declare i32 @scriptgo_arraybuffer_view_buffer(ptr, ptr)
declare i32 @scriptgo_arraybuffer_to_string(ptr, ptr)
declare i32 @scriptgo_typedarray_new(i64, i64, ptr, i64, ptr)
declare i32 @scriptgo_typedarray_get(ptr, double, ptr)
declare i32 @scriptgo_typedarray_get_bigint(ptr, double, ptr)
declare i32 @scriptgo_typedarray_set(ptr, double, double)
declare i32 @scriptgo_typedarray_set_bigint(ptr, double, i64)
declare i32 @scriptgo_typedarray_length(ptr, ptr)
declare i32 @scriptgo_typedarray_byte_length(ptr, ptr)
declare i32 @scriptgo_typedarray_byte_offset(ptr, ptr)
declare i32 @scriptgo_typedarray_buffer(ptr, ptr)
declare i32 @scriptgo_typedarray_subarray(ptr, double, double, ptr)
declare i32 @scriptgo_typedarray_slice(ptr, double, double, ptr)
declare i32 @scriptgo_typedarray_from_array(i64, ptr, ptr)
declare i32 @scriptgo_typedarray_from_typed_array(i64, ptr, ptr)
declare i32 @scriptgo_typedarray_set_array(ptr, ptr, double)
declare i32 @scriptgo_typedarray_set_js_array(ptr, ptr, double)
declare i32 @scriptgo_typedarray_fill(ptr, double, double, double)
declare i32 @scriptgo_typedarray_to_string(ptr, ptr)

`

const declarationsBuffer = `declare i32 @scriptgo_buffer_alloc(double, ptr, double, i32, i32, ptr)
declare i32 @scriptgo_buffer_from_string(ptr, ptr, ptr)
declare i32 @scriptgo_buffer_from_array(ptr, ptr)
declare i32 @scriptgo_buffer_from_arraybuffer(ptr, ptr)
declare i32 @scriptgo_buffer_concat(ptr, double, ptr)
declare i32 @scriptgo_buffer_is_buffer(ptr, ptr)
declare i32 @scriptgo_buffer_byte_length(ptr, ptr, ptr)
declare i32 @scriptgo_buffer_to_string(ptr, ptr, double, double, i32, i32, ptr)
declare i32 @scriptgo_buffer_copy(ptr, ptr, double, double, double, i32, i32, i32, ptr)
declare i32 @scriptgo_buffer_fill(ptr, ptr, double, i32, double, double, i32, i32, ptr)
declare i32 @scriptgo_buffer_equals(ptr, ptr, ptr)
declare i32 @scriptgo_buffer_compare(ptr, ptr, ptr)
declare i32 @scriptgo_buffer_index_of(ptr, ptr, double, i32, double, i32, ptr)
declare i32 @scriptgo_buffer_read_u8(ptr, double, ptr)
declare i32 @scriptgo_buffer_write_u8(ptr, double, double, ptr)
declare i32 @scriptgo_buffer_read_i8(ptr, double, ptr)
declare i32 @scriptgo_buffer_write_i8(ptr, double, double, ptr)
declare i32 @scriptgo_buffer_read_u16(ptr, double, i32, ptr)
declare i32 @scriptgo_buffer_write_u16(ptr, double, double, i32, ptr)
declare i32 @scriptgo_buffer_read_i16(ptr, double, i32, ptr)
declare i32 @scriptgo_buffer_write_i16(ptr, double, double, i32, ptr)
declare i32 @scriptgo_buffer_read_u32(ptr, double, i32, ptr)
declare i32 @scriptgo_buffer_write_u32(ptr, double, double, i32, ptr)
declare i32 @scriptgo_buffer_read_i32(ptr, double, i32, ptr)
declare i32 @scriptgo_buffer_write_i32(ptr, double, double, i32, ptr)
declare i32 @scriptgo_buffer_read_float(ptr, double, i32, ptr)
declare i32 @scriptgo_buffer_write_float(ptr, double, double, i32, ptr)
declare i32 @scriptgo_buffer_read_double(ptr, double, i32, ptr)
declare i32 @scriptgo_buffer_write_double(ptr, double, double, i32, ptr)
declare i32 @scriptgo_buffer_read_bigint64(ptr, double, i32, ptr)
declare i32 @scriptgo_buffer_write_bigint64(ptr, i64, double, i32, ptr)
declare i32 @scriptgo_buffer_read_int(ptr, double, double, i32, i32, ptr)
declare i32 @scriptgo_buffer_write_int(ptr, double, double, double, i32, i32, ptr)
declare i32 @scriptgo_buffer_swap(ptr, i32, ptr)
declare i32 @scriptgo_buffer_last_index_of(ptr, ptr, double, i32, double, i32, ptr)
declare i32 @scriptgo_buffer_includes(ptr, ptr, double, i32, double, i32, ptr)
declare i32 @scriptgo_buffer_write(ptr, ptr, double, double, ptr, ptr)

`

const declarationsDataview = `declare i32 @scriptgo_dataview_new(ptr, double, double, ptr)
declare i32 @scriptgo_dataview_byte_length(ptr, ptr)
declare i32 @scriptgo_dataview_byte_offset(ptr, ptr)
declare i32 @scriptgo_dataview_buffer(ptr, ptr)
declare i32 @scriptgo_dataview_get_int8(ptr, double, ptr)
declare i32 @scriptgo_dataview_set_int8(ptr, double, double)
declare i32 @scriptgo_dataview_get_uint8(ptr, double, ptr)
declare i32 @scriptgo_dataview_set_uint8(ptr, double, double)
declare i32 @scriptgo_dataview_get_int16(ptr, double, i32, ptr)
declare i32 @scriptgo_dataview_set_int16(ptr, double, double, i32)
declare i32 @scriptgo_dataview_get_uint16(ptr, double, i32, ptr)
declare i32 @scriptgo_dataview_set_uint16(ptr, double, double, i32)
declare i32 @scriptgo_dataview_get_int32(ptr, double, i32, ptr)
declare i32 @scriptgo_dataview_set_int32(ptr, double, double, i32)
declare i32 @scriptgo_dataview_get_uint32(ptr, double, i32, ptr)
declare i32 @scriptgo_dataview_set_uint32(ptr, double, double, i32)
declare i32 @scriptgo_dataview_get_float32(ptr, double, i32, ptr)
declare i32 @scriptgo_dataview_set_float32(ptr, double, double, i32)
declare i32 @scriptgo_dataview_get_float64(ptr, double, i32, ptr)
declare i32 @scriptgo_dataview_set_float64(ptr, double, double, i32)
declare i32 @scriptgo_dataview_get_bigint64(ptr, double, i32, ptr)
declare i32 @scriptgo_dataview_set_bigint64(ptr, double, i64, i32)
declare i32 @scriptgo_dataview_get_biguint64(ptr, double, i32, ptr)
declare i32 @scriptgo_dataview_set_biguint64(ptr, double, i64, i32)
declare i32 @scriptgo_dataview_to_string(ptr, ptr)

`

const declarationsMap = `declare i32 @scriptgo_map_new(ptr)
declare i32 @scriptgo_map_new_entries(ptr, ptr)
declare i32 @scriptgo_map_set_string_number(ptr, ptr, double, ptr)
declare i32 @scriptgo_map_set_string_string(ptr, ptr, ptr, ptr)
declare i32 @scriptgo_map_set_string_bigint(ptr, ptr, i64, ptr)
declare i32 @scriptgo_map_set_string_ptr(ptr, ptr, ptr, ptr)
declare i32 @scriptgo_map_set_number_number(ptr, double, double, ptr)
declare i32 @scriptgo_map_set_number_string(ptr, double, ptr, ptr)
declare i32 @scriptgo_map_set_number_ptr(ptr, double, ptr, ptr)
declare i32 @scriptgo_map_get_number(ptr, ptr, double, i32, ptr)
declare i32 @scriptgo_map_get_string(ptr, ptr, double, i32, ptr)
declare i32 @scriptgo_map_get_bigint(ptr, ptr, double, i32, ptr)
declare i32 @scriptgo_map_get_ptr(ptr, ptr, double, i32, ptr)
declare i32 @scriptgo_map_has(ptr, ptr, double, i32, ptr)
declare i32 @scriptgo_map_delete(ptr, ptr, double, i32, ptr)
declare i32 @scriptgo_map_clear(ptr)
declare i32 @scriptgo_map_size(ptr, ptr)
declare i32 @scriptgo_map_to_string(ptr, ptr)
declare i32 @scriptgo_map_for_each(ptr, ptr)
declare i32 @scriptgo_map_keys(ptr, ptr)
declare i32 @scriptgo_map_values(ptr, ptr)
declare i32 @scriptgo_map_entries(ptr, ptr)

`

const declarationsSet = `declare i32 @scriptgo_set_new(ptr)
declare i32 @scriptgo_set_new_values_number(ptr, ptr)
declare i32 @scriptgo_set_new_values_string(ptr, ptr)
declare i32 @scriptgo_set_new_values_ptr(ptr, ptr)
declare i32 @scriptgo_set_add_number(ptr, double, ptr)
declare i32 @scriptgo_set_add_string(ptr, ptr, ptr)
declare i32 @scriptgo_set_add_ptr(ptr, ptr, ptr)
declare i32 @scriptgo_set_has_number(ptr, double, ptr)
declare i32 @scriptgo_set_has_string(ptr, ptr, ptr)
declare i32 @scriptgo_set_has_ptr(ptr, ptr, ptr)
declare i32 @scriptgo_set_delete_number(ptr, double, ptr)
declare i32 @scriptgo_set_delete_string(ptr, ptr, ptr)
declare i32 @scriptgo_set_delete_ptr(ptr, ptr, ptr)
declare i32 @scriptgo_set_clear(ptr)
declare i32 @scriptgo_set_size(ptr, ptr)
declare i32 @scriptgo_set_to_string(ptr, ptr)
declare i32 @scriptgo_set_for_each(ptr, ptr)
declare i32 @scriptgo_set_keys(ptr, ptr)
declare i32 @scriptgo_set_values(ptr, ptr)
declare i32 @scriptgo_set_entries(ptr, ptr)
declare i32 @scriptgo_set_union(ptr, ptr, ptr)
declare i32 @scriptgo_set_intersection(ptr, ptr, ptr)
declare i32 @scriptgo_set_difference(ptr, ptr, ptr)
declare i32 @scriptgo_set_symmetric_difference(ptr, ptr, ptr)
declare i32 @scriptgo_set_is_subset_of(ptr, ptr, ptr)
declare i32 @scriptgo_set_is_superset_of(ptr, ptr, ptr)
declare i32 @scriptgo_set_is_disjoint_from(ptr, ptr, ptr)

`
