package llvm

// Native runtime ABI declarations, emitted verbatim in module order by
// writeRuntimeDeclarations. Keep each block in sync with internal/runtime.

const declarationsConsole = `declare i32 @scriptgo_console_clear()
declare i32 @scriptgo_console_group()
declare i32 @scriptgo_console_group_end()
declare i32 @scriptgo_console_count(ptr)
declare i32 @scriptgo_console_count_reset(ptr)
declare i32 @scriptgo_console_time(ptr)
declare i32 @scriptgo_console_time_log(ptr, ptr)
declare i32 @scriptgo_console_time_end(ptr)
declare i32 @scriptgo_console_trace(ptr)

`

const declarationsFail = `declare void @__scriptgo_fail_checked_cast(i32, i32, ptr)
declare ptr @__scriptgo_typeof_unknown(ptr)
declare i32 @scriptgo_is_truthy_unknown(ptr)
declare i32 @scriptgo_closure_equals(ptr, ptr)
declare i32 @scriptgo_string_from_unknown(ptr, ptr)
declare i32 @scriptgo_string_from_object(ptr, ptr)

`

const declarationsLLVMIntrinsics = `declare double @llvm.fabs.f64(double)
declare double @llvm.ceil.f64(double)
declare double @llvm.floor.f64(double)
declare double @llvm.trunc.f64(double)
declare double @llvm.sqrt.f64(double)
declare double @llvm.round.f64(double)
declare double @llvm.sin.f64(double)
declare double @llvm.cos.f64(double)
declare double @llvm.log.f64(double)
declare double @llvm.log2.f64(double)
declare double @llvm.log10.f64(double)
declare double @llvm.exp.f64(double)
declare double @tan(double)
declare double @atan(double)
declare double @asin(double)
declare double @acos(double)
declare double @cbrt(double)
declare double @sinh(double)
declare double @cosh(double)
declare double @tanh(double)
declare double @asinh(double)
declare double @acosh(double)
declare double @atanh(double)
declare double @expm1(double)
declare double @log1p(double)
declare double @atan2(double, double)
declare double @hypot(double, double)
declare double @llvm.minimum.f64(double, double)
declare double @llvm.maximum.f64(double, double)
declare double @scriptgo_math_round(double)
declare double @scriptgo_math_pow(double, double)
declare double @drand48()
declare i32 @llvm.ctlz.i32(i32, i1)

`

const declarationsNumber = `declare i32 @scriptgo_number_parse_int(ptr, ptr)
declare i32 @scriptgo_number_parse_int_radix(ptr, double, ptr)
declare i32 @scriptgo_number_parse_float(ptr, ptr)
declare double @scriptgo_string_to_number(ptr)
declare i32 @scriptgo_array_search_bool(ptr, i32, double, i32, ptr)
declare i32 @scriptgo_array_search_value(ptr, ptr, double, i32, ptr)
declare double @scriptgo_value_to_number(ptr)
declare double @scriptgo_object_to_number(ptr)
declare i32 @scriptgo_number_is_nan(double, ptr)
declare i32 @scriptgo_number_is_finite(double, ptr)
declare i32 @scriptgo_number_is_integer(double, ptr)
declare i32 @scriptgo_number_is_safe_integer(double, ptr)
declare i32 @scriptgo_number_to_fixed(double, double, ptr)
declare i32 @scriptgo_number_to_string(double, double, ptr)
declare i32 @scriptgo_number_to_exponential(double, double, ptr)
declare i32 @scriptgo_number_to_precision(double, double, ptr)
declare i32 @scriptgo_number_to_locale_string(double, ptr)
declare i32 @scriptgo_to_int32(double) readnone nounwind willreturn

`

const declarationsArray = `declare i32 @scriptgo_array_new(i64, i64, ptr)
declare i32 @scriptgo_array_set_tag(ptr, i64)
declare i32 @scriptgo_array_get(ptr, double, ptr)
declare i32 @scriptgo_array_set(ptr, double, ptr)
declare i32 @scriptgo_array_set_typed(ptr, double, ptr, i64, i64)
declare i32 @scriptgo_array_length(ptr, ptr)
declare i32 @scriptgo_array_set_length(ptr, double)
declare i32 @scriptgo_array_push(ptr, ptr, ptr)
declare i32 @scriptgo_array_pop(ptr, ptr)
declare i32 @scriptgo_array_slice(ptr, double, double, ptr)
declare i32 @scriptgo_array_slice_with_size(ptr, double, double, i64, ptr)
declare i32 @scriptgo_array_index_of_number(ptr, double, double, ptr)
declare i32 @scriptgo_array_index_of_string(ptr, ptr, double, ptr)
declare i32 @scriptgo_array_index_of_ptr(ptr, ptr, double, ptr)
declare i32 @scriptgo_array_includes_number(ptr, double, ptr)
declare i32 @scriptgo_array_includes_string(ptr, ptr, ptr)
declare i32 @scriptgo_array_includes_ptr(ptr, ptr, ptr)
declare i32 @scriptgo_array_at(ptr, double, ptr)
declare i32 @scriptgo_array_shift(ptr, ptr)
declare i32 @scriptgo_array_unshift(ptr, ptr, ptr)
declare i32 @scriptgo_array_reverse(ptr, ptr)
declare i32 @scriptgo_array_concat(ptr, ptr, ptr)
declare i32 @scriptgo_array_splice(ptr, double, double, ptr)
declare i32 @scriptgo_array_join_number(ptr, ptr, ptr)
declare i32 @scriptgo_array_join_string(ptr, ptr, ptr)
declare i32 @scriptgo_array_join_bigint(ptr, ptr, ptr)
declare i32 @scriptgo_array_join_unknown(ptr, ptr, ptr)
declare i32 @scriptgo_array_keys(ptr, ptr)
declare i32 @scriptgo_array_entries(ptr, ptr)
declare i32 @scriptgo_array_release(ptr)

`

const declarationsObject = `declare i32 @scriptgo_object_new(i64, ptr)
declare i32 @scriptgo_object_new_typed(i64, ptr, ptr)
declare ptr @scriptgo_object_new_typed_fast(i64, ptr)
declare i32 @scriptgo_object_freeze(ptr, ptr)
declare i32 @scriptgo_object_seal(ptr, ptr)
declare i32 @scriptgo_object_prevent_extensions(ptr, ptr)
declare i32 @scriptgo_object_is_frozen(ptr, ptr)
declare i32 @scriptgo_object_is_sealed(ptr, ptr)
declare i32 @scriptgo_object_is_extensible(ptr, ptr)
declare i32 @scriptgo_object_number_set(ptr, i64, double)
declare i32 @scriptgo_object_number_get(ptr, i64, ptr)
declare i32 @scriptgo_object_string_set(ptr, i64, ptr)
declare i32 @scriptgo_object_string_get(ptr, i64, ptr)
declare i32 @scriptgo_object_bool_set(ptr, i64, i32)
declare i32 @scriptgo_object_bool_get(ptr, i64, ptr)
declare i32 @scriptgo_object_bigint_set(ptr, i64, i64)
declare i32 @scriptgo_object_bigint_get(ptr, i64, ptr)
declare i32 @scriptgo_object_ptr_set(ptr, i64, ptr)
declare i32 @scriptgo_object_ptr_get(ptr, i64, ptr)
declare i32 @scriptgo_object_unknown_set(ptr, i64, ptr)
declare i32 @scriptgo_object_unknown_get(ptr, i64, ptr)
declare i32 @scriptgo_object_property_unknown_get(ptr, ptr, ptr)
declare i32 @scriptgo_object_property_number_get(ptr, ptr, ptr)
declare i32 @scriptgo_object_property_string_get(ptr, ptr, ptr)
declare i32 @scriptgo_object_property_string_set(ptr, ptr, ptr)
declare i32 @scriptgo_object_property_bool_get(ptr, ptr, ptr)
declare i32 @scriptgo_object_property_bigint_get(ptr, ptr, ptr)
declare i32 @scriptgo_object_property_ptr_get(ptr, ptr, ptr)
declare i32 @scriptgo_object_property_number_set(ptr, ptr, double)
declare i32 @scriptgo_object_property_bool_set(ptr, ptr, i32)
declare i32 @scriptgo_object_property_bigint_set(ptr, ptr, i64)
declare i32 @scriptgo_object_property_ptr_set(ptr, ptr, ptr)
declare i32 @scriptgo_object_property_unknown_set(ptr, ptr, ptr)
declare i32 @scriptgo_object_delete_property(ptr, ptr, ptr)
declare i32 @scriptgo_unknown_number_property(ptr, ptr, ptr)
declare i32 @scriptgo_object_type_set(ptr, ptr)
declare i32 @scriptgo_object_type_set_static(ptr, ptr)
declare i32 @scriptgo_object_type_get(ptr, ptr)
declare i32 @scriptgo_object_instanceof(ptr, ptr, ptr)
declare i32 @scriptgo_object_is_number(double, double, ptr)
declare i32 @scriptgo_object_is_string(ptr, ptr, ptr)
declare i32 @scriptgo_object_is_ptr(ptr, ptr, ptr)
declare ptr @scriptgo_object_get_prototype(ptr)
declare ptr @scriptgo_object_get_prototype_value(ptr)
declare i32 @scriptgo_object_is_prototype_of(ptr, ptr)
declare i32 @scriptgo_object_reflect_set(ptr, ptr, ptr, ptr)
declare i32 @scriptgo_object_has_own(ptr, ptr, ptr)
declare i32 @scriptgo_object_values(ptr, i64, i64, ptr)
declare i32 @scriptgo_object_entries(ptr, ptr)
declare i32 @scriptgo_object_reflect_delete(ptr, ptr, ptr)
declare i32 @scriptgo_object_is_unknown(ptr, ptr, ptr)
declare i32 @scriptgo_object_equals_unknown(ptr, ptr, i32, ptr)
declare i32 @scriptgo_object_keys(ptr, ptr)
declare i32 @scriptgo_object_group_by(ptr, ptr, ptr)
declare i32 @scriptgo_object_release(ptr)

`

const declarationsJson = `declare i32 @scriptgo_json_stringify_number(double, ptr)
declare i32 @scriptgo_json_stringify_bool(i32, ptr)
declare i32 @scriptgo_json_stringify_string(ptr, ptr)
declare i32 @scriptgo_json_stringify_number_array(ptr, ptr)
declare i32 @scriptgo_json_stringify_string_array(ptr, ptr)
declare i32 @scriptgo_json_stringify_object_array(ptr, ptr)
declare i32 @scriptgo_json_stringify_unknown(ptr, ptr)
declare i32 @scriptgo_json_parse_unknown(ptr, ptr)

`

const declarationsString = `declare i32 @scriptgo_string_concat(ptr, ptr, ptr)
declare i32 @scriptgo_string_length(ptr, ptr)
declare i32 @scriptgo_string_index_of(ptr, ptr, double, ptr)
declare i32 @scriptgo_string_last_index(ptr, ptr, double, ptr)
declare i32 @scriptgo_string_starts_with(ptr, ptr, ptr)
declare i32 @scriptgo_string_ends_with(ptr, ptr, ptr)
declare i32 @scriptgo_string_char_at(ptr, double, ptr)
declare i32 @scriptgo_string_char_code_at(ptr, double, ptr)
declare i32 @scriptgo_string_code_point_at(ptr, double, ptr)
declare i32 @scriptgo_string_from_code_point(double, ptr)
declare i32 @scriptgo_string_is_well_formed(ptr, ptr)
declare i32 @scriptgo_string_to_well_formed(ptr, ptr)
declare i32 @scriptgo_string_normalize(ptr, ptr, ptr)
declare i32 @scriptgo_string_includes(ptr, ptr, double, ptr)
declare i32 @scriptgo_string_to_lower(ptr, ptr)
declare i32 @scriptgo_string_to_upper(ptr, ptr)
declare i32 @scriptgo_string_trim_start(ptr, ptr)
declare i32 @scriptgo_string_trim_end(ptr, ptr)
declare i32 @scriptgo_string_repeat(ptr, double, ptr)
declare i32 @scriptgo_string_replace_all(ptr, ptr, ptr, ptr)
declare i32 @scriptgo_string_pad_start(ptr, double, ptr, ptr)
declare i32 @scriptgo_string_pad_end(ptr, double, ptr, ptr)
declare i32 @scriptgo_string_from_number(double, ptr)
declare i32 @scriptgo_string_from_bigint(i64, ptr)
declare i32 @scriptgo_string_from_bigint_locale(i64, ptr)
declare i32 @scriptgo_error_to_string(ptr, ptr)
declare i32 @scriptgo_error_capture_stack(ptr, ptr, ptr)
declare i32 @scriptgo_string_from_bool(i32, ptr)
declare i32 @scriptgo_string_slice(ptr, double, double, ptr)
declare i32 @scriptgo_string_trim(ptr, ptr)
declare i32 @scriptgo_string_replace(ptr, ptr, ptr, ptr)
declare i32 @scriptgo_string_replace_regex(ptr, ptr, ptr, ptr, ptr)
declare i32 @scriptgo_string_match(ptr, ptr, ptr, ptr)
declare i32 @scriptgo_string_search(ptr, ptr, ptr, ptr)
declare i32 @scriptgo_string_split(ptr, ptr, double, ptr)
declare i32 @scriptgo_string_substr(ptr, double, double, ptr)
declare i32 @scriptgo_string_from_char_codes(ptr, i64, ptr)
declare i32 @scriptgo_string_at(ptr, double, ptr)
declare i32 @scriptgo_string_anchor(ptr, ptr, ptr)
declare i32 @scriptgo_string_big(ptr, ptr)
declare i32 @scriptgo_string_blink(ptr, ptr)
declare i32 @scriptgo_string_bold(ptr, ptr)
declare i32 @scriptgo_string_fixed(ptr, ptr)
declare i32 @scriptgo_string_fontcolor(ptr, ptr, ptr)
declare i32 @scriptgo_string_fontsize(ptr, ptr, ptr)
declare i32 @scriptgo_string_italics(ptr, ptr)
declare i32 @scriptgo_string_link(ptr, ptr, ptr)
declare i32 @scriptgo_string_small(ptr, ptr)
declare i32 @scriptgo_string_strike(ptr, ptr)
declare i32 @scriptgo_string_sub(ptr, ptr)
declare i32 @scriptgo_string_sup(ptr, ptr)
declare i32 @scriptgo_string_encode_uri_component(ptr, ptr)
declare i32 @scriptgo_string_decode_uri_component(ptr, ptr)
declare i32 @scriptgo_string_encode_uri(ptr, ptr)
declare i32 @scriptgo_string_decode_uri(ptr, ptr)
declare i32 @scriptgo_string_release(ptr)
declare i32 @scriptgo_string_compare(ptr, ptr)

`

const declarationsRegex = `declare i32 @scriptgo_regex_test(ptr, ptr, ptr, ptr)
declare i32 @scriptgo_regex_exec(ptr, ptr, ptr, ptr)
declare i32 @scriptgo_regex_exec_stateful(ptr, ptr, ptr, ptr, ptr)
declare i32 @scriptgo_bigint_from_number(double, ptr)
declare i32 @scriptgo_bigint_from_string(ptr, ptr)
declare i32 @scriptgo_bigint_as_int_n(i64, i64, ptr)
declare i32 @scriptgo_bigint_as_uint_n(i64, i64, ptr)
declare i64 @scriptgo_bigint_pow(i64, i64)

`

const declarationsSymbol = `declare i32 @scriptgo_symbol_create(ptr, ptr)
declare i32 @scriptgo_symbol_for(ptr, ptr)
declare i32 @scriptgo_symbol_key_for(ptr, ptr)
declare i32 @scriptgo_symbol_description(ptr, ptr)
declare i32 @scriptgo_symbol_to_string(ptr, ptr)

`

const declarationsFs = `declare i32 @scriptgo_fs_read_file_sync(ptr, ptr, ptr)
declare i32 @scriptgo_fs_read_file_buffer_sync(ptr, ptr)
declare i32 @scriptgo_fs_write_file_sync(ptr, ptr)
declare i32 @scriptgo_fs_exists_sync(ptr, ptr)
declare i32 @scriptgo_fs_unlink_sync(ptr)
declare i32 @scriptgo_fs_stat_sync(ptr, ptr, ptr, ptr, ptr)
declare i32 @scriptgo_fs_readdir_sync(ptr, ptr)
declare i32 @scriptgo_fs_copy_file_sync(ptr, ptr)
declare i32 @scriptgo_fs_rename_sync(ptr, ptr)
declare i32 @scriptgo_fs_append_file_sync(ptr, ptr)
declare i32 @scriptgo_fs_mkdir_sync(ptr, double)
declare i32 @scriptgo_fs_rm_sync(ptr, double, double)
declare i32 @scriptgo_fs_access_sync(ptr, double, ptr)
declare i32 @scriptgo_fs_chmod_sync(ptr, double)
declare i32 @scriptgo_fs_realpath_sync(ptr, ptr)
declare i32 @scriptgo_fs_truncate_sync(ptr, double)
declare i32 @scriptgo_fs_mkdtemp_sync(ptr, ptr)
declare i32 @scriptgo_fs_open_sync(ptr, ptr, double, ptr)
declare i32 @scriptgo_fs_close_sync(double)
declare i32 @scriptgo_fs_read_fd_sync(double, ptr, double, double, double, ptr)
declare i32 @scriptgo_fs_write_fd_sync(double, ptr, double, double, ptr)
declare i32 @scriptgo_fs_opendir_sync(ptr, ptr, ptr)
declare i32 @scriptgo_fs_fstat_sync(double, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare i32 @scriptgo_fs_statfs_sync(ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare i32 @scriptgo_fs_chown_sync(ptr, double, double)
declare i32 @scriptgo_fs_lchown_sync(ptr, double, double)
declare i32 @scriptgo_fs_fchown_sync(double, double, double)
declare i32 @scriptgo_fs_fchmod_sync(double, double)
declare i32 @scriptgo_fs_link_sync(ptr, ptr)
declare i32 @scriptgo_fs_symlink_sync(ptr, ptr)
declare i32 @scriptgo_fs_readlink_sync(ptr, ptr)
declare i32 @scriptgo_fs_utimes_sync(ptr, double, double)
declare i32 @scriptgo_fs_lutimes_sync(ptr, double, double)
declare i32 @scriptgo_fs_futimes_sync(double, double, double)
declare i32 @scriptgo_fs_fsync_sync(double)
declare i32 @scriptgo_fs_fdatasync_sync(double)
declare i32 @scriptgo_fs_ftruncate_sync(double, double)
declare i32 @scriptgo_fs_rmdir_sync(ptr)
declare i32 @scriptgo_fs_watch_create(ptr, ptr)
declare i32 @scriptgo_fs_watch_poll(double, ptr, ptr, ptr)
declare i32 @scriptgo_fs_watch_close(double)

`

const declarationsProcess = `declare void @scriptgo_process_init(i32, ptr)
declare i32 @scriptgo_process_exit(double)
declare i32 @scriptgo_process_cwd(ptr)
declare i32 @scriptgo_process_argv(ptr)
declare i32 @scriptgo_process_env(ptr, ptr)
declare i32 @scriptgo_process_set_env(ptr, ptr)

`

const declarationsChild = `declare i32 @scriptgo_child_process_exec_sync(ptr, ptr, ptr, ptr, ptr, ptr)
declare i32 @scriptgo_child_process_spawn_sync(ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare i32 @scriptgo_child_process_spawn_async(ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare i32 @scriptgo_child_process_poll_status(double, ptr, ptr)
declare i32 @scriptgo_child_process_pipe_read(double, double, ptr, ptr, ptr)
declare i32 @scriptgo_child_process_pipe_write(double, ptr, double, ptr)
declare i32 @scriptgo_child_process_pipe_close(double)
declare i32 @scriptgo_child_process_kill(double, double, ptr)

`

const declarationsDns = `declare i32 @scriptgo_dns_lookup(ptr, double, ptr, ptr)
declare i32 @scriptgo_dns_lookup_all(ptr, double, ptr, ptr)
declare i32 @scriptgo_dns_lookup_service(ptr, double, ptr, ptr)
declare i32 @scriptgo_dns_reverse(ptr, ptr)
declare i32 @scriptgo_dns_resolve_strings(ptr, ptr, ptr)
declare i32 @scriptgo_dns_resolve_mx(ptr, ptr, ptr)
declare i32 @scriptgo_dns_resolve_txt(ptr, ptr)
declare i32 @scriptgo_dns_resolve_srv(ptr, ptr, ptr, ptr, ptr)
declare i32 @scriptgo_dns_resolve_soa(ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare i32 @scriptgo_dns_resolve_caa(ptr, ptr, ptr)
declare i32 @scriptgo_dns_resolve_naptr(ptr, ptr, ptr, ptr, ptr, ptr, ptr)

`

const declarationsNet = `declare i32 @scriptgo_net_socket_create(double, double, ptr)
declare i32 @scriptgo_net_socket_connect(double, ptr, double)
declare i32 @scriptgo_net_socket_write(double, ptr, double, ptr)
declare i32 @scriptgo_net_socket_read(double, double, ptr, ptr)
declare i32 @scriptgo_net_socket_close(double)
declare i32 @scriptgo_net_socket_set_nodelay(double, double)
declare i32 @scriptgo_net_socket_set_keepalive(double, double, double)
declare i32 @scriptgo_net_server_listen(ptr, double, double, ptr)
declare i32 @scriptgo_net_server_accept(double, ptr, ptr, ptr)

`

const declarationsDgram = `declare i32 @scriptgo_dgram_socket_create(double, ptr)
declare i32 @scriptgo_dgram_bind(double, ptr, double)
declare i32 @scriptgo_dgram_send(double, ptr, double, double, ptr, ptr)
declare i32 @scriptgo_dgram_recv(double, double, ptr, ptr, ptr, ptr, ptr)
declare i32 @scriptgo_dgram_set_broadcast(double, double)
declare i32 @scriptgo_dgram_set_multicast_ttl(double, double)
declare i32 @scriptgo_dgram_set_multicast_loopback(double, double)
declare i32 @scriptgo_dgram_set_recv_buffer_size(double, double)
declare i32 @scriptgo_dgram_set_send_buffer_size(double, double)
declare i32 @scriptgo_dgram_get_recv_buffer_size(double, ptr)
declare i32 @scriptgo_dgram_get_send_buffer_size(double, ptr)
declare i32 @scriptgo_dgram_set_ttl(double, double)
declare i32 @scriptgo_dgram_set_multicast_interface(double, ptr)
declare i32 @scriptgo_dgram_add_membership(double, ptr, ptr)
declare i32 @scriptgo_dgram_drop_membership(double, ptr, ptr)
declare i32 @scriptgo_dgram_add_source_specific_membership(double, ptr, ptr, ptr)
declare i32 @scriptgo_dgram_drop_source_specific_membership(double, ptr, ptr, ptr)
declare i32 @scriptgo_dgram_connect(double, ptr, double)
declare i32 @scriptgo_dgram_disconnect(double)
declare i32 @scriptgo_dgram_close(double)

`

const declarationsTls = `declare i32 @scriptgo_tls_context_create(ptr, ptr, ptr, ptr, ptr, ptr, double, ptr)
declare i32 @scriptgo_tls_socket_create(double, double, ptr)
declare i32 @scriptgo_tls_socket_connect(double, ptr, double, ptr, double, ptr, ptr)
declare i32 @scriptgo_tls_socket_adopt(double, double, ptr, double, double, double, ptr, ptr)
declare i32 @scriptgo_tls_socket_write(double, ptr, double, ptr)
declare i32 @scriptgo_tls_socket_write_bytes(double, ptr, ptr)
declare i32 @scriptgo_tls_socket_read(double, double, ptr)
declare i32 @scriptgo_tls_socket_pair_write(double, double, ptr, double, ptr)
declare i32 @scriptgo_tls_socket_pair_write_bytes(double, double, ptr, ptr)
declare i32 @scriptgo_tls_socket_pair_read(double, double, double, ptr)
declare i32 @scriptgo_tls_socket_close(double)
declare i32 @scriptgo_tls_socket_info(double, ptr, ptr)
declare i32 @scriptgo_tls_socket_number(double, ptr, ptr)
declare i32 @scriptgo_tls_socket_bool(double, ptr, ptr)
declare i32 @scriptgo_tls_socket_export_keying_material(double, double, ptr, ptr, ptr)
declare i32 @scriptgo_tls_socket_set_option(double, ptr, double)
declare i32 @scriptgo_tls_socket_set_servername(double, ptr)
declare i32 @scriptgo_tls_socket_set_session(double, ptr)
declare i32 @scriptgo_tls_socket_set_key_cert(double, ptr, ptr)
declare i32 @scriptgo_tls_socket_renegotiate(double, ptr)
declare i32 @scriptgo_tls_pair_create(double, double, double, double, ptr)
declare i32 @scriptgo_tls_server_listen(double, double, double, ptr, double, double, ptr)
declare i32 @scriptgo_tls_server_accept(double, ptr)
declare i32 @scriptgo_tls_server_close(double)
declare i32 @scriptgo_tls_server_info(double, ptr, ptr)
declare i32 @scriptgo_tls_server_set_context(double, double, double, double)
declare i32 @scriptgo_tls_server_add_context(double, ptr, double)
declare i32 @scriptgo_tls_server_set_ticket_keys(double, ptr)
declare i32 @scriptgo_tls_x509_parse_pem(ptr, ptr)
declare i32 @scriptgo_tls_x509_parse_bytes(ptr, ptr)
declare i32 @scriptgo_tls_ciphers(ptr)
declare i32 @scriptgo_tls_root_certificates(ptr)

declare i32 @scriptgo_tls_system_certificates(ptr)
declare i32 @scriptgo_tls_extra_certificates(ptr)

`
